### ISSUE TITLE
”Chain-based" mode can not output communication time

### ISSUE THREAD

**Issue by DaichiYamazaki538** [azu-lab/RD-Gen#27]
設定ファイルで通信時間を指定したところ、
Chain-basedモードでは通信時間が出力されませんでした。
設定ファイルと結果のファイルを提示しておきます。

設定ファイル
```
Seed: 0
Number of DAGs: 1

Graph structure:
  Generation method: "Chain-based"
  Number of chains:
    Combination: (6, 10, 2)
  Main sequence length:
    Random: (2, 12, 1)
  Number of sub sequences:
    Fixed: 0
  Vertically link chains:
    Number of entry nodes:
      Random: (3, 8, 1)
    Main sequence tail: True
    Sub sequence tail: True
  Merge chains:
    Number of exit nodes:
      Fixed: 1
    Middle of chain: True
    Exit node: True

Properties:
  Execution time:
    Random: (100, 5000, 1)
  Communication time:
    Random: (100, 500, 1)
  Multi-rate:
    Periodic type: 'Chain'
    Period:
      Random: [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
    Offset:
      Random: (100, 5000, 100)
    Total utilization:
      Random: (4.0, 8.0, 0.1)

Output formats:
  Naming of combination directory: "Abbreviation"
  DAG:
    YAML: True
    JSON: False
    XML: False
    DOT: False
  Figure:
    Draw legend: False
    PNG: True
    SVG: False
    EPS: False
    PDF: False

```

結果
```
directed: true
graph: {}
links:
- source: 0
  target: 1
- source: 1
  target: 2
- source: 2
  target: 3
- source: 3
  target: 4
- source: 4
  target: 5
- source: 5
  target: 6
- source: 6
  target: 7
- source: 7
  target: 35
- source: 8
  target: 9
- source: 9
  target: 10
- source: 10
  target: 11
- source: 11
  target: 12
- source: 12
  target: 13
- source: 13
  target: 14
- source: 14
  target: 15
- source: 15
  target: 17
- source: 16
  target: 17
- source: 18
  target: 19
- source: 19
  target: 20
- source: 20
  target: 21
- source: 21
  target: 22
- source: 22
  target: 23
- source: 23
  target: 2
- source: 24
  target: 25
- source: 25
  target: 26
- source: 26
  target: 27
- source: 27
  target: 28
- source: 28
  target: 29
- source: 29
  target: 30
- source: 30
  target: 31
- source: 31
  target: 32
- source: 32
  target: 33
- source: 33
  target: 1
- source: 34
  target: 35
- source: 35
  target: 36
- source: 36
  target: 37
- source: 37
  target: 38
- source: 38
  target: 39
- source: 39
  target: 40
- source: 40
  target: 41
- source: 41
  target: 42
- source: 42
  target: 9
multigraph: false
nodes:
- execution_time: 88
  id: 0
  offset: 400
  period: 10000
- execution_time: 5
  id: 1
  offset: 4400
- execution_time: 128
  id: 2
  offset: 1100
- execution_time: 8
  id: 3
  offset: 1100
- execution_time: 495
  id: 4
  offset: 2200
- execution_time: 1458
  id: 5
  offset: 3400
- execution_time: 1
  id: 6
  offset: 1700
- execution_time: 5
  id: 7
  offset: 800
- execution_time: 17
  id: 8
  offset: 3900
  period: 10000
- execution_time: 8
  id: 9
  offset: 2900
- execution_time: 1000
  id: 10
  offset: 4300
- execution_time: 26
  id: 11
  offset: 1200
- execution_time: 3044
  id: 12
  offset: 100
- execution_time: 41
  id: 13
  offset: 3100
- execution_time: 29
  id: 14
  offset: 4400
- execution_time: 33
  id: 15
  offset: 2700
- execution_time: 1577
  id: 16
  offset: 3700
  period: 2000
- execution_time: 857
  id: 17
  offset: 3300
- execution_time: 3
  id: 18
  offset: 2000
  period: 6000
- execution_time: 200
  id: 19
  offset: 4200
- execution_time: 39
  id: 20
  offset: 2300
- execution_time: 300
  id: 21
  offset: 2500
- execution_time: 4
  id: 22
  offset: 4300
- execution_time: 2
  id: 23
  offset: 1700
- execution_time: 35
  id: 24
  offset: 1000
  period: 9000
- execution_time: 50
  id: 25
  offset: 3600
- execution_time: 1
  id: 26
  offset: 4500
- execution_time: 2
  id: 27
  offset: 100
- execution_time: 1
  id: 28
  offset: 3000
- execution_time: 1
  id: 29
  offset: 4800
- execution_time: 1
  id: 30
  offset: 600
- execution_time: 36
  id: 31
  offset: 2200
- execution_time: 48
  id: 32
  offset: 4800
- execution_time: 46
  id: 33
  offset: 300
- execution_time: 299
  id: 34
  offset: 3500
  period: 2000
- execution_time: 3761
  id: 35
  offset: 1800
- execution_time: 24
  id: 36
  offset: 900
- execution_time: 19
  id: 37
  offset: 1600
- execution_time: 26
  id: 38
  offset: 4900
- execution_time: 81
  id: 39
  offset: 3100
- execution_time: 589
  id: 40
  offset: 2300
- execution_time: 786
  id: 41
  offset: 4000
- execution_time: 70
  id: 42
  offset: 1900

```
